## 00 pytorch fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


https://docs.pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector.shape

torch.Size([2])

In [6]:
matrix = torch.tensor([[7, 7],
                       [6, 7]])

matrix

tensor([[7, 7],
        [6, 7]])

In [7]:
matrix.shape

torch.Size([2, 2])

In [8]:
matrix.ndim

2

In [9]:
tensor = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
print(f"{tensor}")
print(f"tensor with shape: {tensor.shape}")



tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor with shape: torch.Size([1, 3, 3])


In [10]:
print(f"accessing the 1st dimension:\n {tensor[0]}")
print(f"accessing the 2nd row:\n {tensor[0][1]}")
print(f"accessing the 3rd column:\n {tensor[0][:, 2]}")
print(f"accessing the 1st item in the 3rd row:\n {tensor[0][2][0]}")

accessing the 1st dimension:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
accessing the 2nd row:
 tensor([4, 5, 6])
accessing the 3rd column:
 tensor([3, 6, 9])
accessing the 1st item in the 3rd row:
 7


In [11]:
tensor_1 = torch.tensor([[[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 11, 12, 13]],

                         [[10, 20, 30, 40],
                          [31, 41, 51, 61],
                          [62, 72, 84, 96]]])
tensor_1

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 11, 12, 13]],

        [[10, 20, 30, 40],
         [31, 41, 51, 61],
         [62, 72, 84, 96]]])

In [12]:
tensor_1.shape

torch.Size([2, 3, 4])

In [13]:
print(f"accessing the 2nd row of the 1st dimension:\n {tensor_1[0][1]}")
print(f"accessing the 4th column of the 2nd dimension:\n {tensor_1[1][:, 3]}")

accessing the 2nd row of the 1st dimension:
 tensor([5, 6, 7, 8])
accessing the 4th column of the 2nd dimension:
 tensor([40, 61, 96])


In [14]:
matrix_1 = torch.tensor([[7, 7],
                         [6, 7]])
matrix_2 = torch.tensor([[5, 6],
                         [4, 2]])
print(f"multiplied:\n {matrix_1 * matrix_2}")

multiplied:
 tensor([[35, 42],
        [24, 14]])


In [15]:
matrix_3 = torch.tensor([[3, 4, 5],
                         [4, 3, 6]])
matrix_4 = torch.tensor([[2, 3],
                         [4, 5],
                         [9, 2]])
print(f"shapes of matrix 3 and matrix 4:\n {matrix_3.shape, matrix_4.shape}")
print(f"dot product of matrix 3 and matrix 4:\n {matrix_3 @ matrix_4}")
print(f"dot product of matrix 4 and matrix 3:\n {matrix_4 @ matrix_3}")

shapes of matrix 3 and matrix 4:
 (torch.Size([2, 3]), torch.Size([3, 2]))
dot product of matrix 3 and matrix 4:
 tensor([[67, 39],
        [74, 39]])
dot product of matrix 4 and matrix 3:
 tensor([[18, 17, 28],
        [32, 31, 50],
        [35, 42, 57]])


In [16]:
matrix_5 = torch.tensor([[7, 7, 7],
                         [6, 5, 7]])
matrix_6 = torch.tensor([[4, 5],
                         [6, 5],
                         [4, 3],
                         [3, 7]])
matrix_7 = matrix_6 @ matrix_5
print(f"Size Matrix 5: {matrix_5.shape} | Size Matrix 6: {matrix_6.shape}")
print(f"dot product of matrix 6 and matrix 5:\n {matrix_6 @ matrix_5}")
print(f"no dot product of matrix 5 and matrix 6 due to mismatch of inner dimensions")
print(f"matching ineer dimension gives matrix in shape outer dimensions:\n {matrix_7.shape}")


Size Matrix 5: torch.Size([2, 3]) | Size Matrix 6: torch.Size([4, 2])
dot product of matrix 6 and matrix 5:
 tensor([[58, 53, 63],
        [72, 67, 77],
        [46, 43, 49],
        [63, 56, 70]])
no dot product of matrix 5 and matrix 6 due to mismatch of inner dimensions
matching ineer dimension gives matrix in shape outer dimensions:
 torch.Size([4, 3])


In [17]:
# random tensors
torch.manual_seed(123)
ran_tensor = torch.rand(size=(2, 5, 6))
print(f"random tensor:\n{ran_tensor}")
print(f"random tensor in shape:\n{ran_tensor.shape}")
print(f"accessing 1st batch:\n{ran_tensor[0]}\n")
tensor_second_batch = ran_tensor[1]
print(f"accessing 2nd batch:\n{tensor_second_batch}\n")
norm_tensor_row_second_batch = tensor_second_batch.softmax(dim=1)
print(f"2nd batch normalized along the rows:\n{norm_tensor_row_second_batch}\n")
norm_tensor_row_second_batch_sum = sum(norm_tensor_row_second_batch[1])
print(f"sum of 2nd row:\n{norm_tensor_row_second_batch_sum:.4f}\n")
norm_tensor_col_second_batch = tensor_second_batch.softmax(dim=0)
print(f"2nd batch normalized along the columns:\n{norm_tensor_col_second_batch}\n")
norm_tensor_col_second_batch_sum = sum(norm_tensor_col_second_batch[:, 1])
print(f"sum of 2nd column:\n{norm_tensor_col_second_batch_sum:.4f}")

random tensor:
tensor([[[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665],
         [0.1366, 0.1025, 0.1841, 0.7264, 0.3153, 0.6871],
         [0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274],
         [0.3821, 0.6605, 0.8536, 0.5932, 0.6367, 0.9826],
         [0.2745, 0.6584, 0.2775, 0.8573, 0.8993, 0.0390]],

        [[0.9268, 0.7388, 0.7179, 0.7058, 0.9156, 0.4340],
         [0.0772, 0.3565, 0.1479, 0.5331, 0.4066, 0.2318],
         [0.4545, 0.9737, 0.4606, 0.5159, 0.4220, 0.5786],
         [0.9455, 0.8057, 0.6775, 0.6087, 0.6179, 0.6932],
         [0.4354, 0.0353, 0.1908, 0.9268, 0.5299, 0.0950]]])
random tensor in shape:
torch.Size([2, 5, 6])
accessing 1st batch:
tensor([[0.2961, 0.5166, 0.2517, 0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841, 0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164, 0.4017, 0.1186, 0.8274],
        [0.3821, 0.6605, 0.8536, 0.5932, 0.6367, 0.9826],
        [0.2745, 0.6584, 0.2775, 0.8573, 0.8993, 0.0390]])

accessing 2nd batch:
tensor([[0.

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)
unsqueezed_random_image_size_tensor = random_image_size_tensor.unsqueeze(0)
print(f"unsqueezed:\n{unsqueezed_random_image_size_tensor.shape}")
squeeze_random_image_size_tensor = unsqueezed_random_image_size_tensor.squeeze()
print(f"squeezed:\n{squeeze_random_image_size_tensor.shape}")




torch.Size([224, 224, 3]) 3
unsqueezed:
torch.Size([1, 224, 224, 3])
squeezed:
torch.Size([224, 224, 3])


In [19]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
torch.manual_seed(123)
random_tensor = torch.rand(size=(5, 3))
random_tensor

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871],
        [0.0756, 0.1966, 0.3164]])

In [21]:
print(f"{zeros.shape}, {random_tensor.shape}")
res = random_tensor @ zeros
print(f"Random Tensor @ Zeros:\n{random_tensor @ zeros}")
print(f"Order is crucial when calculating dot product, make inner dimensions (3, 3) -> result (5 X 4) Matrix")
print(res.size())

torch.Size([3, 4]), torch.Size([5, 3])
Random Tensor @ Zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Order is crucial when calculating dot product, make inner dimensions (3, 3) -> result (5 X 4) Matrix
torch.Size([5, 4])


In [22]:
ones = torch.ones(size=(5, 4))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [23]:
torch.manual_seed(42)
random_tensor_1 = torch.rand(size=(8, 4))
random_tensor_1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753]])

In [24]:
print(f"shape ones: {ones.shape}\nshape random: {random_tensor_1.shape}\n")
print(f"shape ones transposed: {ones.T.shape}\nshape random: {random_tensor_1.shape}\n")
print(f"can calculate dot product of {random_tensor_1.shape} @ {ones.T.shape}")
res_ones_t = random_tensor_1 @ ones.T
res_ones_t
print(f"Random tensor 1 {random_tensor_1.shape} @ ones transposed {ones.T.shape} gives shape {res_ones_t.shape}\n")
print(f"shape ones: {ones.shape}\nshape random transposed: {random_tensor_1.T.shape}\n")
print(f"can calculate dot product of {ones.shape} @ {random_tensor_1.T.shape}")
res_rand_t = ones @ random_tensor_1.T
res_rand_t
print(f"ones {ones.shape} @ random tensor 1 {random_tensor_1.T.shape} gives shape {res_rand_t.shape}\n")


shape ones: torch.Size([5, 4])
shape random: torch.Size([8, 4])

shape ones transposed: torch.Size([4, 5])
shape random: torch.Size([8, 4])

can calculate dot product of torch.Size([8, 4]) @ torch.Size([4, 5])
Random tensor 1 torch.Size([8, 4]) @ ones transposed torch.Size([4, 5]) gives shape torch.Size([8, 5])

shape ones: torch.Size([5, 4])
shape random transposed: torch.Size([4, 8])

can calculate dot product of torch.Size([5, 4]) @ torch.Size([4, 8])
ones torch.Size([5, 4]) @ random tensor 1 torch.Size([4, 8]) gives shape torch.Size([5, 8])



In [25]:
tensor_3 = torch.tensor([[1, 2],
                         [3, 4]])
tensor_4 = torch.tensor([5., 6., 7.])

print(tensor_3.dtype)
print(tensor_4.dtype)


torch.int64
torch.float32


## creating tensors and tensors-like

In [26]:
tens_range = torch.arange(1, 11)
print(f"Using arange function to create range: {tens_range}")
tens_range_step = torch.arange(start=0, end=28, step=3)
print(f"Using arange and steps to create range: {tens_range_step}")

Using arange function to create range: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Using arange and steps to create range: tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])


In [27]:
ten_ones = torch.ones_like(tens_range_step)
print(ten_ones)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [28]:
ten_zeros = torch.zeros_like(ten_ones)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
float_32_tensor = torch.tensor([3., 6., 9.],
                               dtype=None, # defaults to float 32
                               device=None, # defaults to cpu
                               requires_grad=False)
print(f"tensor\n{float_32_tensor} is by default of data type {float_32_tensor.dtype}")
float_16_tensor = float_32_tensor.type(torch.float16)
print(f"tensor type can be changed:\n{float_32_tensor} with new data type {float_16_tensor.dtype}")

tensor
tensor([3., 6., 9.]) is by default of data type torch.float32
tensor type can be changed:
tensor([3., 6., 9.]) with new data type torch.float16


In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
tensor_float_16 = torch.tensor([3., 6., 9.],
                               dtype=torch.float16,
                               device="cpu",
                               requires_grad=False)
print(f"specifying data type while building tensor:\n{tensor_float_16}")

specifying data type while building tensor:
tensor([3., 6., 9.], dtype=torch.float16)


In [32]:
res_tensor = float_32_tensor * float_16_tensor
res_tensor.dtype
print(f"multiplying {float_32_tensor.dtype} * {float_16_tensor.dtype} gives {res_tensor.dtype}")


multiplying torch.float32 * torch.float16 gives torch.float32


In [33]:
matrix_77 = torch.tensor([[1, 2, 3],
                          [3, 2, 4]])
tensor_76 = torch.tensor([7, 7, 7])
print(f"{matrix_77}\n{tensor_76}")
print(f"matrix type: {matrix_77.dtype}\nvector type: {tensor_76.dtype}")
matrix_77 @ tensor_76

tensor([[1, 2, 3],
        [3, 2, 4]])
tensor([7, 7, 7])
matrix type: torch.int64
vector type: torch.int64


tensor([42, 63])

In [34]:
tensor_int_32 = torch.tensor([3, 2, 4], dtype=torch.int32)
print(f"tensor {tensor_int_32} of type int 32: {tensor_int_32.dtype}")
tensor_int_64 = torch.tensor([3, 2, 4], dtype=torch.int64)
print(f"tensor {tensor_int_64} of type int 64: {tensor_int_64.dtype}")
tensor_float_16 = torch.tensor([3., 4., 5.], dtype=torch.float16)
print(f"tensor {tensor_float_16} of type float 16: {tensor_float_16.dtype}")
tensor_float_32 = torch.tensor([3., 4., 5.], dtype=torch.float32)
print(f"tensor {tensor_float_32} of type {tensor_float_32.dtype}")
res_1 = tensor_int_32 * tensor_int_64
res_2 = tensor_int_32 * tensor_float_16
print(f"tensor type {tensor_int_32.dtype} * tensor {tensor_int_64.dtype} gives {res_1.dtype}")
print(f"tensor type {tensor_int_32.dtype} * tensor {tensor_float_16.dtype} gives {res_2.dtype}")


tensor tensor([3, 2, 4], dtype=torch.int32) of type int 32: torch.int32
tensor tensor([3, 2, 4]) of type int 64: torch.int64
tensor tensor([3., 4., 5.], dtype=torch.float16) of type float 16: torch.float16
tensor tensor([3., 4., 5.]) of type torch.float32
tensor type torch.int32 * tensor torch.int64 gives torch.int64
tensor type torch.int32 * tensor torch.float16 gives torch.float16


In [35]:
tensor_long = torch.tensor([3, 4, 5], dtype=torch.long)
tensor_64 = torch.tensor([3, 4, 5])
print(f"torch.long gives out 64bit tensor: {tensor_long.dtype}")
print(f"matching default value of dtype: {tensor_64.dtype}")

torch.long gives out 64bit tensor: torch.int64
matching default value of dtype: torch.int64


### getting information from tensors

In [36]:
tensor_23 = torch.rand(4, 7)
print(tensor_23)
print(f"Tensor Data Type: {tensor_23.dtype}")
print(f"Tensor Shape: {tensor_23.shape}") # shape -> attribute
print(f"Tensor Size: {tensor_23.size()}") # size() -> function
print(f"Tensor on device: {tensor_23.device} by default.")

tensor([[0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814],
        [0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165],
        [0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447]])
Tensor Data Type: torch.float32
Tensor Shape: torch.Size([4, 7])
Tensor Size: torch.Size([4, 7])
Tensor on device: cpu by default.


In [37]:
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [39]:
tensor_33 = torch.rand(6, 6)
tensor_34 = torch.rand(5, 6).type(torch.float16)
print(f"defautl data type: {tensor_33.dtype}")
print(f"default data type changed to: {tensor_34.dtype}")
tensor_35 = torch.rand([5, 6])
print(f"tensor on: {tensor_35.device} (default device)")
# tensor_36 = torch.rand([5, 6], device="cuda") # only if cuda is available
# print(f"tensor on: {tensor_36.device} (set to the device)")


defautl data type: torch.float32
default data type changed to: torch.float16
tensor on: cpu (default device)


### manipulating tensors (tensor operations)

In [41]:
add_to_tensor = torch.tensor([[1, 2, 3],
                              [2, 3, 4],
                              [4, 3, 6]])
added_10 = add_to_tensor + 10
added_10

tensor([[11, 12, 13],
        [12, 13, 14],
        [14, 13, 16]])

### using built in function

In [53]:
mul_tensor = torch.mul(added_10, 4)
print(f"torch.mul function:\n{mul_tensor}")
div_tensor = torch.div(mul_tensor, 2)
print(f"torch.div function:\n{div_tensor}")
add_to_tensor = torch.add(mul_tensor, div_tensor)
print(f"adding 2 tensors using torch.add function:\n{add_to_tensor}")
sub_tensor = torch.sub(div_tensor, mul_tensor)
print(f"subtracting one tensor from another:\n{sub_tensor}")

torch.mul function:
tensor([[44, 48, 52],
        [48, 52, 56],
        [56, 52, 64]])
torch.div function:
tensor([[22., 24., 26.],
        [24., 26., 28.],
        [28., 26., 32.]])
adding 2 tensors using torch.add function:
tensor([[66., 72., 78.],
        [72., 78., 84.],
        [84., 78., 96.]])
subtracting one tensor from another:
tensor([[-22., -24., -26.],
        [-24., -26., -28.],
        [-28., -26., -32.]])


### matrix multiplication

* element-wise multiplication -> multiply each element of the matrix by a number
* matrix multiplication using dot product

In [79]:
matrix_43 = torch.tensor([[2, 3, 4],
                          [4, 5, 6]])
print(f"matrix 43:\n{matrix_43}")
print(f"shape of matrix 43\n{matrix_43.shape}\n")
matrix_44 = torch.tensor([[[3, 4],
                           [4, 5],
                           [8, 3]]])
print(f"matrix 44:\n{matrix_44}")
print(f"shape of matrix 44:\n{matrix_44.shape}\n")

res_mat_mul = torch.matmul(matrix_43, matrix_44)
print(f"result matmul matrix 43 and matrix 44:\n{res_mat_mul}\nwith shape {res_mat_mul.shape}\n")
res_mat_mul_1 = torch.matmul(matrix_43, matrix_44.squeeze())
print(f"result matmul matrix 43 and matrix 44 squeezed\n{res_mat_mul_1}\nwith shape {res_mat_mul_1.shape}\n")
res_mat_mul_2 = torch.matmul(matrix_43, matrix_44.unsqueeze(0))
print(f"result matmul matrix 43 and matrix 44 unsqueezed\n{res_mat_mul_2}\nwith shape {res_mat_mul_2.shape}")


matrix 43:
tensor([[2, 3, 4],
        [4, 5, 6]])
shape of matrix 43
torch.Size([2, 3])

matrix 44:
tensor([[[3, 4],
         [4, 5],
         [8, 3]]])
shape of matrix 44:
torch.Size([1, 3, 2])

result matmul matrix 43 and matrix 44:
tensor([[[50, 35],
         [80, 59]]])
with shape torch.Size([1, 2, 2])

result matmul matrix 43 and matrix 44 squeezed
tensor([[50, 35],
        [80, 59]])
with shape torch.Size([2, 2])

result matmul matrix 43 and matrix 44 unsqueezed
tensor([[[[50, 35],
          [80, 59]]]])
with shape torch.Size([1, 1, 2, 2])


In [84]:
matrix_21 = torch.tensor([[2, 3],
                          [2, 3]])
matrix_45 = torch.tensor([[4, 5],
                          [8, 2]])
res_21_45 = torch.matmul(matrix_21, matrix_45)
print(res_21_45)
res_21_45_1 = matrix_21 @ matrix_45
print(res_21_45_1)

tensor([[32, 16],
        [32, 16]])
tensor([[32, 16],
        [32, 16]])


In [ ]:
# arange
# max
# min
# mean
# sum
# argmax
# reshape
# view
# stack -> hstack, vstack
# permute
# from_numpy / numpy