#  00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.0.0


In [2]:
## Introduction to tensors

### Creating Tensors

https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# tensor as python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [4, 6]])
MATRIX

tensor([[7, 8],
        [4, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3], # dim 0 = pink, dim 1 = blue, dim 3 = yellow
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**scalar** -> a single number;
number dimensions = 0

**vector** -> a number with direction (can have many numbers (only 1 row));
number of dimensions = 1

**MATRIX** -> 2-dimensional array of numbers;
number of dimensions = 2

**TENSOR** -> can be any number, a 0 dimensional tensor is a scalar, a 1 dimensional tensor is a vector

**Random Tensors**

Why random tensors, they are important because the way neural networks learn is that they start of

with tensors full of random numbers and the adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> update random numbers

https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# Create random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8167, 0.7262, 0.9511, 0.2091],
        [0.0186, 0.4885, 0.7582, 0.2154],
        [0.1680, 0.1301, 0.0321, 0.8386]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel (r, g, b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
# can be done with the size attribute or without
tensor1 = torch.rand(size=(3, 4))
tensor2 = torch.rand(10, 3)
tensor1

tensor([[0.5643, 0.3206, 0.4567, 0.8359],
        [0.4525, 0.6252, 0.0042, 0.2423],
        [0.8988, 0.4262, 0.7201, 0.5346]])

In [21]:
tensor2

tensor([[0.4243, 0.7894, 0.0889],
        [0.5300, 0.1128, 0.5019],
        [0.5092, 0.1209, 0.8406],
        [0.7879, 0.5053, 0.4150],
        [0.0130, 0.8577, 0.2162],
        [0.4902, 0.7801, 0.5619],
        [0.7724, 0.0977, 0.0702],
        [0.2910, 0.9018, 0.9297],
        [0.3442, 0.3682, 0.4746],
        [0.4066, 0.8816, 0.8769]])

In [22]:
# Zeros and Ones

In [23]:
zero = torch.zeros(size=(8, 3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
ones = torch.ones(size=(5, 5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
# Creating a range of tensors and tensor-like
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

https://docs.pytorch.org/docs/stable/generated/torch.arange.html

In [27]:
tensor_with_step = torch.arange(start=1, end=1000, step=77)
tensor_with_step

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [28]:
# Creating tensors like -> recreating the shape of a tensor with all zeros
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor data types

NOTE: Tensor datatypes is one of the 3 big errors with PyTorch and DeepLearning:

1. Tensors not the right datatype
2. Tensors not the right shape
3. Tensors not the right device

Precision in computing
https://en.wikipedia.org/wiki/Precision_(computer_science)



In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,            # what datatype is the tensor (e.g. float32 or float16)
                               device=None,           # what device is your tensor on
                               requires_grad=False)   # whether or not to track gradients with this tensors operations
float_32_tensor = float_32_tensor.type(torch.float32)
float_32_tensor

tensor([3., 6., 9.])

https://docs.pytorch.org/docs/stable/tensors.html

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

getting information from tensors (attributes)

 1. Tensors not the right datatype - to get datatype from a tensor can use tensor.dtype
 2. Tensors not the right shape - to get shape from tensor can use tensor.shape
 3. Tensors not the right device - to get device form tensor can use tensor.device

In [35]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8837, 0.3579, 0.0709, 0.1290],
        [0.1286, 0.5676, 0.9141, 0.8045],
        [0.4448, 0.7625, 0.4393, 0.7776]])

In [36]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor = {some_tensor.dtype}")
print(f"Shape of tensor = {some_tensor.shape}")
print(f"Device tensor is on = {some_tensor.device}")

tensor([[0.8837, 0.3579, 0.0709, 0.1290],
        [0.1286, 0.5676, 0.9141, 0.8045],
        [0.4448, 0.7625, 0.4393, 0.7776]])
Datatype of tensor = torch.float32
Shape of tensor = torch.Size([3, 4])
Device tensor is on = cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [37]:
# create tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# multiply
tensor * 10

tensor([10, 20, 30])

In [39]:
# subtract
tensor - 10

tensor([-9, -8, -7])

In [40]:
# pytorch built-in multiplication method
tensor_mul = torch.mul(tensor, 5)
tensor_mul

tensor([ 5, 10, 15])

In [41]:
# pytorch built-in addition method
tensor_add = torch.add(tensor_mul, 5)
tensor_add

tensor([10, 15, 20])

In [42]:
# pytorch built-in subtraction method
tensor_sub = torch.sub(tensor_add, 5)
tensor_sub

tensor([ 5, 10, 15])

In [43]:
# pytorch built-in division method
tensor_div = torch.div(tensor_sub, 5)
tensor_div

tensor([1., 2., 3.])

In [44]:
tensor_1 = torch.sub(tensor_add, tensor_mul)
tensor_1

tensor([5, 5, 5])

https://statmath.wu.ac.at/~leydold/MOK/HTML/node17.html

https://www.mathebibel.de/matrizenmultiplikation

http://matrixmultiplication.xyz/

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

 1. Element-wise multiplication
 2. Matrix multiplication (dot-product)

 there are two rules that matrix multiplication must satisfy
 - inner dimensions have to match
   
    (3, 2) @ (2, 3) -> will work
    
    (3, 2) @ (3, 2) -> will NOT work
    
    (2, 3) @ (3, 2) -> will work
  
  - resulting matrix has the shape of the outher dimensions

    (3, 2) @ (2, 3) -> (3, 3)

    (2, 3) @ (3, 2) -> (2, 2)

In [45]:
res_tensor = torch.rand(2, 3) @ torch.rand(3, 3)
res_tensor

tensor([[1.1576, 1.4578, 0.4112],
        [0.5746, 0.8827, 0.4903]])

In [46]:
res_tensor = torch.rand(2, 3) @ torch.rand(3, 3)
res_tensor

tensor([[0.9577, 0.9961, 0.8535],
        [1.1761, 1.1679, 1.1890]])

In [47]:
res_tensor1 = torch.rand(3, 2) @ torch.rand(2, 3)
res_tensor1

tensor([[1.1612, 1.1726, 0.8790],
        [0.7399, 0.6930, 0.5454],
        [0.6650, 0.7154, 0.5152]])

In [48]:
res_tensor1.shape

torch.Size([3, 3])

In [49]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# get to the result by hand
1*1 + 2*2 + 3*3

14

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 588 μs, sys: 705 μs, total: 1.29 ms
Wall time: 1.38 ms


In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 87 μs, sys: 15 μs, total: 102 μs
Wall time: 86.8 μs


tensor(14)

In [55]:
%%time
tensor @ tensor

CPU times: user 105 μs, sys: 23 μs, total: 128 μs
Wall time: 120 μs


tensor(14)

In [56]:
### one of the most common errors in deep learning is shape errors -> inner dimensions must match (check with .shape)

In [57]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [58]:
tensor_A, tensor_B.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [59]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


# ** transpose ** switches rows and columns in matrices

In [60]:
# torch.mm(tensor_A, tensor_B) torch.mm is short version for torch.matmul used in matrix multiplication

resA_BT = torch.matmul(tensor_A, tensor_B.T)
print(f"{tensor_A.shape} @ {tensor_B.T.shape} -> inner dimensions match -> result of shape outer dimensions {resA_BT.shape}")
print(resA_BT)

torch.Size([3, 2]) @ torch.Size([2, 3]) -> inner dimensions match -> result of shape outer dimensions torch.Size([3, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [61]:
resAT_B = torch.mm(tensor_A.T, tensor_B)
print(f"{tensor_A.T.shape} @ {tensor_B.shape} -> inner dimensions match -> result of shape outer dimensions {resAT_B.shape}")
print(resAT_B)


torch.Size([2, 3]) @ torch.Size([3, 2]) -> inner dimensions match -> result of shape outer dimensions torch.Size([2, 2])
tensor([[ 76, 103],
        [100, 136]])


In [62]:
print(tensor_B, "\n")
print(tensor_B.shape, "\n")
print(tensor_B.T, "\n")
print(tensor_B.T.shape)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]]) 

torch.Size([3, 2]) 

tensor([[ 7,  8,  9],
        [10, 11, 12]]) 

torch.Size([2, 3])


how to transpose first column

( 1, 1 [ 7 ] ) -> ( 1, 1 );

( 2, 1 [ 8 ] ) -> ( 1, 2 );
                    
( 3, 1 [ 9 ] ) -> ( 1, 3 );

how to transpose second column

( 1, 2 [ 10 ] ) -> ( 2, 1 );

( 2, 2 [ 11 ] ) -> ( 2, 2 );
                    
( 3, 2 [ 12 ] ) -> ( 2, 3 );



## Finding ther min, max, mean, sum (Tensor aggregation)

In [63]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [64]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [65]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [66]:
# find mean -> requires a tensor of float 32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [67]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [68]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
# finds position with minimum value with argmin() -> returns index position , value also displayed
x.argmin(), x[0]

(tensor(0), tensor(0))

In [70]:
# finds position with maximum value with argmax() -> returns index position , value also displayed
x.argmax(), x[9]

(tensor(9), tensor(90))

## reshaping, stacking, squeezing and unsqueezing tensors

https://docs.pytorch.org/docs/stable/generated/torch.stack.html

* reshaping -> reshapes tensor to a defined shape

* view -> return a view of an input tensor of a certain shape but keep the same memory as the original tensor

* stacking -> combine multiple tensors on top of each other (vstack) or side by side (hstack)

* unsqueeze -> add a 1 dimension to the target tensor

* permute -> return a view of the input with dimensions permuted (swapped) in a certain way

In [71]:
# creating tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [72]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
x_reshaped1 = x.reshape(3, 3) # has to be multipliers of the original size 9
x_reshaped1, x_reshaped1.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [74]:
# change the view, similar to reshape but z shares the same memory -> changing z changes x as well
z = x.view(1, 9)
z, z.shape
z[:, 0] = 5 # changing an element in the tensor of z, : includes the whole tensor [0] gets the position of the element which wants to be changed
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
# stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [76]:
x_stacked_v = torch.vstack([x, x, x, x])
x_stacked_v

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
x_stacked_h = torch.hstack([x, x, x, x])
x_stacked_h

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [79]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(x_reshaped)
print(x_reshaped.shape, "original","\n")
x_reshaped_sq = x_reshaped.squeeze()
print(x_reshaped_sq)
print(x_reshaped_sq.shape, "squeezed","\n")
print("removes the single dimension from a tensor\n")
x_reshaped_usq_0 = x_reshaped_sq.unsqueeze(dim=0) # takes the dimension vaue , set to 0 or -+1
print(x_reshaped_usq_0)
print(x_reshaped_usq_0.shape, "unsqueezed along dimension 0","\n")
x_reshaped_usq_1 = x_reshaped_sq.unsqueeze(dim=1) # takes the dimension vaue , set to 0 or -+1
print(x_reshaped_usq_1)
print(x_reshaped_usq_1.shape, "unsqueezed along dimension 1","\n")

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9]) original 

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9]) squeezed 

removes the single dimension from a tensor

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9]) unsqueezed along dimension 0 

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1]) unsqueezed along dimension 1 



In [80]:
# torch.permute() rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channel]

# permute the original tensor to rearrange the order of dimensions
print(x_original.size())
print(f"Switched the first dimension with the third dimension: {torch.permute(x_original,(2, 0, 1)).shape}") # mind the difference between .size() and .shape
print(f"Switched the second dimension with the third dimension: {torch.permute(x_original,(1, 2, 0)).size()}")

torch.Size([224, 224, 3])
Switched the first dimension with the third dimension: torch.Size([3, 224, 224])
Switched the second dimension with the third dimension: torch.Size([224, 3, 224])


In [81]:
x_ori = torch.rand(size=(4, 3, 3))
x_per = x_ori.permute(2, 0, 1)
x_ori
x_per
x_ori[0,0,0] = 100
x_per

tensor([[[1.0000e+02, 3.8891e-01, 6.9329e-01],
         [1.3971e-01, 3.5863e-01, 3.8066e-01],
         [6.7933e-02, 4.1635e-01, 5.1988e-02],
         [6.9793e-01, 6.8973e-01, 7.0374e-01]],

        [[5.7431e-01, 7.8781e-01, 3.0130e-01],
         [1.6609e-02, 4.1124e-01, 3.2890e-01],
         [4.0868e-01, 4.6696e-01, 5.7471e-01],
         [6.1088e-01, 2.8971e-01, 4.3616e-01]],

        [[3.0434e-01, 6.7330e-01, 4.1850e-01],
         [3.7667e-01, 8.6232e-01, 7.3036e-01],
         [2.2244e-01, 7.2064e-01, 3.4142e-01],
         [3.0227e-01, 9.0890e-01, 8.6384e-01]]])

## Indexing (selecting data from Tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [82]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
# indexing on the tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
x[0, 0], x[0][0] # dim=1

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [85]:
x[0, -1, -1], x[0][-1][-1], x[0, 2, 2], x[0][2][2]

(tensor(9), tensor(9), tensor(9), tensor(9))

In [86]:
# you can also use the ":" to select ALL of the target dimension
x[:, 0] # extracting a row from the tensor

tensor([[1, 2, 3]])

In [87]:
x[:, :, 0], x[:, :, 0].T  # extracting columns from tensors

(tensor([[1, 4, 7]]),
 tensor([[1],
         [4],
         [7]]))

In [88]:
# get all values of the zero dimension but only the 1 index value of 1st and 2nd dimension
print(x[:, 1, 1]) # mind the square brackets using the colon for selecting whole dimensions instead of the 0
print(x[0, 1, 1])
print(x[0][1][1])

tensor([5])
tensor(5)
tensor(5)


In [89]:
# get index 0 of 0th dimension and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [90]:
print(x[0, 2, 2])
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tesors and NumPy

NumPy is a popular scientific Python numerical computing library

PyTorch has functionality to interact with numpy

- Data un NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

- PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [109]:
# NumPy array to tensor
import torch
import numpy as np
print(np.__version__)

array = np.arange(1.0, 8.0) # original numpy array
tensor = torch.from_numpy(array).type(torch.float32) # default is 64 WARNING: when converting from numpy -> pytorch, pytorch reflects the numpy's default datatype of float64 unless specified otherwise
array.dtype, tensor.dtype

1.26.0


(dtype('float64'), torch.float32)

In [92]:
print(array.dtype)
print(tensor.dtype)

float64
torch.float64


In [93]:
# change the value of array, what will happen to tensor
array = array + 1
array, tensor # -> changing the array does not change the tensor as this is created new and separate in memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
# tensor to numpy array
tensor = torch.ones(7) # original torch tensor
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
numpy_tensor.dtype

dtype('float32')

In [96]:
# change the tensor, what happens to numpy tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

https://docs.pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

## Reproducability -> trying to take random out of random

https://docs.pytorch.org/docs/stable/notes/randomness.html

In short how a neural network learns
`start with random nuumbers -> tensor operations -> update random numbers and try to make them better representations of the data -> again -> again ...

to reduce the randomness in neural networks and pytorch comes a concept of **random seed**

random seed flavours the randomness


In [97]:
torch.rand(3, 3)

tensor([[0.9425, 0.3286, 0.2592],
        [0.1422, 0.7991, 0.0622],
        [0.1197, 0.0590, 0.8385]])

In [98]:
import torch
# create two random tnesors
a = torch.rand(3, 4)
b = torch.rand(3, 4)

print(a)
print(b)
print(a == b)

tensor([[0.3262, 0.3966, 0.0144, 0.3738],
        [0.8740, 0.8215, 0.4435, 0.7938],
        [0.7378, 0.1753, 0.5233, 0.6950]])
tensor([[0.8908, 0.2637, 0.7355, 0.1064],
        [0.8860, 0.2471, 0.5227, 0.8640],
        [0.9743, 0.5523, 0.7124, 0.9814]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [99]:
# Let's make random but reproducable tensors
import torch

# ste random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
d = torch.rand(3, 4)

print(c)
print(d)
print(c==d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


https://docs.pytorch.org/docs/stable/generated/torch.rand.html

https://en.wikipedia.org/wiki/Random_seed


## running tensors and pytorch objects on gpus and making faster computation

gpus = faster computation on numbers,
thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky

### 1. getting a gpu

1. Easiest use google colab for a free gpu
2. use own gpu - must be set up
3. use cloud computing - gcp, aws, azure, these services allow you to rent computers on the cloud and access them

for 2, 3 pytorch + gpu drivers takes setting up , refer to pytorch set up doc
https://pytorch.org/get-started/locally/


In [100]:
!nividia-smi # not running on gpu at the moment

zsh:1: command not found: nividia-smi


In [101]:
# check for gpu access with pytorch
import torch
torch.cuda.is_available()

False

In [102]:
# set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [103]:
# count number of devices
torch.cuda.device_count()

0

https://docs.pytorch.org/docs/stable/notes/cuda.html

For pytorch since it is capable of running compute on the gpu or cpu, it is best practice to setup device agnostic code.

E.g. run on GPU if available, else default to CPU -> cell 224

## putting tensors and models on the gpu

gpu are doing great on numerical operations which is why we want to use them

In [104]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

# tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [105]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device) # widley used
tensor_on_gpu

tensor([1, 2, 3])

### Moving tensors back to cpu

In [106]:
# if tensor on the GPU, can't transform to numPy
tensor_on_gpu.numpy() # because it is not really on gpu because not available, otherwise would have errored

array([1, 2, 3])

In [107]:
# moving the tensr from the gpu back to the cpu -> might want to try this out when the gpu is working
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])